<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\Exposure;
use App\Enums\Level;
use App\Enums\PlantEnvironment;
use App\Models\Plant;
use Illuminate\Database\Seeder;

class PlantSeeder extends Seeder
{
    public function run(): void
    {
        $plants = [
            [
                'name' => 'Monstera deliciosa',
                'species' => 'Monstera deliciosa',
                'description' => 'Une plante graphique aux grandes feuilles découpées.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::PARTIAL_SHADE,
                'watering_level' => Level::MEDIUM,
                'maintenance_level' => Level::MEDIUM,
                'adult_height_cm' => 180,
                'adult_width_cm' => 100,
                'price' => '34.90',
                'stock_quantity' => 8,
                'is_active' => true,
            ],
            [
                'name' => 'Sansevieria Laurentii',
                'species' => 'Dracaena trifasciata',
                'description' => 'Une plante robuste qui tolère les oublis d’arrosage.',
                'environment' => PlantEnvironment::BOTH,
                'exposure' => Exposure::SUN,
                'watering_level' => Level::LOW,
                'maintenance_level' => Level::LOW,
                'adult_height_cm' => 90,
                'adult_width_cm' => 35,
                'price' => '19.90',
                'stock_quantity' => 14,
                'is_active' => true,
            ],
            [
                'name' => 'Calathea Orbifolia',
                'species' => 'Goeppertia orbifolia',
                'description' => 'Un feuillage décoratif pour une lumière douce et régulière.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::SHADE,
                'watering_level' => Level::HIGH,
                'maintenance_level' => Level::HIGH,
                'adult_height_cm' => 70,
                'adult_width_cm' => 60,
                'price' => '29.90',
                'stock_quantity' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Pothos doré',
                'species' => 'Epipremnum aureum',
                'description' => 'Une liane généreuse, facile à installer sur une étagère ou en suspension.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::PARTIAL_SHADE,
                'watering_level' => Level::LOW,
                'maintenance_level' => Level::LOW,
                'adult_height_cm' => 40,
                'adult_width_cm' => 35,
                'price' => '16.90',
                'stock_quantity' => 18,
                'is_active' => true,
            ],
            [
                'name' => 'Ficus elastica Robusta',
                'species' => 'Ficus elastica',
                'description' => 'Un feuillage ample et brillant pour structurer un intérieur lumineux.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::SUN,
                'watering_level' => Level::MEDIUM,
                'maintenance_level' => Level::MEDIUM,
                'adult_height_cm' => 140,
                'adult_width_cm' => 80,
                'price' => '32.90',
                'stock_quantity' => 6,
                'is_active' => true,
            ],
            [
                'name' => 'Plante araignée',
                'species' => 'Chlorophytum comosum',
                'description' => 'Une plante retombante vive et tolérante, idéale pour débuter.',
                'environment' => PlantEnvironment::BOTH,
                'exposure' => Exposure::PARTIAL_SHADE,
                'watering_level' => Level::MEDIUM,
                'maintenance_level' => Level::LOW,
                'adult_height_cm' => 45,
                'adult_width_cm' => 45,
                'price' => '14.90',
                'stock_quantity' => 20,
                'is_active' => true,
            ],
            [
                'name' => 'Areca',
                'species' => 'Dypsis lutescens',
                'description' => 'Un palmier touffu qui apporte une présence tropicale aux grands espaces.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::PARTIAL_SHADE,
                'watering_level' => Level::MEDIUM,
                'maintenance_level' => Level::MEDIUM,
                'adult_height_cm' => 170,
                'adult_width_cm' => 100,
                'price' => '39.90',
                'stock_quantity' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Zamioculcas',
                'species' => 'Zamioculcas zamiifolia',
                'description' => 'Une plante graphique qui supporte les oublis d’arrosage et les pièces peu lumineuses.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::SHADE,
                'watering_level' => Level::LOW,
                'maintenance_level' => Level::LOW,
                'adult_height_cm' => 100,
                'adult_width_cm' => 60,
                'price' => '27.90',
                'stock_quantity' => 10,
                'is_active' => true,
            ],
            [
                'name' => 'Pachira aquatica',
                'species' => 'Pachira aquatica',
                'description' => 'Un petit arbre d’intérieur reconnaissant avec un feuillage élégant.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::PARTIAL_SHADE,
                'watering_level' => Level::MEDIUM,
                'maintenance_level' => Level::MEDIUM,
                'adult_height_cm' => 160,
                'adult_width_cm' => 80,
                'price' => '39.90',
                'stock_quantity' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Dracaena marginata',
                'species' => 'Dracaena marginata',
                'description' => 'Une silhouette élancée pour donner de la hauteur aux pièces lumineuses.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::SUN,
                'watering_level' => Level::LOW,
                'maintenance_level' => Level::LOW,
                'adult_height_cm' => 150,
                'adult_width_cm' => 60,
                'price' => '26.90',
                'stock_quantity' => 7,
                'is_active' => true,
            ],
            [
                'name' => 'Peperomia obtusifolia',
                'species' => 'Peperomia obtusifolia',
                'description' => 'Un feuillage compact et charnu pour les petits espaces lumineux.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::PARTIAL_SHADE,
                'watering_level' => Level::LOW,
                'maintenance_level' => Level::LOW,
                'adult_height_cm' => 35,
                'adult_width_cm' => 30,
                'price' => '15.90',
                'stock_quantity' => 12,
                'is_active' => true,
            ],
            [
                'name' => 'Fittonia rose',
                'species' => 'Fittonia albivenis',
                'description' => 'Une petite plante colorée qui apprécie une atmosphère humide et une lumière douce.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::SHADE,
                'watering_level' => Level::HIGH,
                'maintenance_level' => Level::HIGH,
                'adult_height_cm' => 25,
                'adult_width_cm' => 25,
                'price' => '12.90',
                'stock_quantity' => 9,
                'is_active' => true,
            ],
            [
                'name' => 'Spathiphyllum',
                'species' => 'Spathiphyllum wallisii',
                'description' => 'Un feuillage dense et des fleurs blanches pour les coins sans soleil direct.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::SHADE,
                'watering_level' => Level::HIGH,
                'maintenance_level' => Level::MEDIUM,
                'adult_height_cm' => 80,
                'adult_width_cm' => 50,
                'price' => '22.90',
                'stock_quantity' => 8,
                'is_active' => true,
            ],
            [
                'name' => 'Aloe vera',
                'species' => 'Aloe barbadensis miller',
                'description' => 'Une succulente solaire qui demande peu d’eau et beaucoup de lumière.',
                'environment' => PlantEnvironment::BOTH,
                'exposure' => Exposure::SUN,
                'watering_level' => Level::LOW,
                'maintenance_level' => Level::LOW,
                'adult_height_cm' => 45,
                'adult_width_cm' => 35,
                'price' => '18.90',
                'stock_quantity' => 11,
                'is_active' => true,
            ],
            [
                'name' => 'Echeveria élégante',
                'species' => 'Echeveria elegans',
                'description' => 'Une rosette compacte pour une fenêtre très lumineuse ou une terrasse abritée.',
                'environment' => PlantEnvironment::BOTH,
                'exposure' => Exposure::SUN,
                'watering_level' => Level::LOW,
                'maintenance_level' => Level::LOW,
                'adult_height_cm' => 15,
                'adult_width_cm' => 15,
                'price' => '9.90',
                'stock_quantity' => 25,
                'is_active' => true,
            ],
            [
                'name' => 'Lavande vraie',
                'species' => 'Lavandula angustifolia',
                'description' => 'Une plante parfumée et résistante pour une exposition extérieure ensoleillée.',
                'environment' => PlantEnvironment::OUTDOOR,
                'exposure' => Exposure::SUN,
                'watering_level' => Level::LOW,
                'maintenance_level' => Level::LOW,
                'adult_height_cm' => 60,
                'adult_width_cm' => 50,
                'price' => '13.90',
                'stock_quantity' => 16,
                'is_active' => true,
            ],
            [
                'name' => 'Romarin officinal',
                'species' => 'Salvia rosmarinus',
                'description' => 'Une aromatique méditerranéenne sobre et productive pour balcon ou jardin.',
                'environment' => PlantEnvironment::OUTDOOR,
                'exposure' => Exposure::SUN,
                'watering_level' => Level::LOW,
                'maintenance_level' => Level::LOW,
                'adult_height_cm' => 70,
                'adult_width_cm' => 50,
                'price' => '11.90',
                'stock_quantity' => 14,
                'is_active' => true,
            ],
            [
                'name' => 'Hortensia bleu',
                'species' => 'Hydrangea macrophylla',
                'description' => 'Une floraison généreuse pour les extérieurs frais et lumineux sans soleil brûlant.',
                'environment' => PlantEnvironment::OUTDOOR,
                'exposure' => Exposure::PARTIAL_SHADE,
                'watering_level' => Level::HIGH,
                'maintenance_level' => Level::MEDIUM,
                'adult_height_cm' => 120,
                'adult_width_cm' => 100,
                'price' => '24.90',
                'stock_quantity' => 6,
                'is_active' => true,
            ],
            [
                'name' => 'Bambou non traçant',
                'species' => 'Fargesia rufa',
                'description' => 'Un bambou dense et non invasif pour créer une présence végétale sur la terrasse.',
                'environment' => PlantEnvironment::OUTDOOR,
                'exposure' => Exposure::SUN,
                'watering_level' => Level::MEDIUM,
                'maintenance_level' => Level::MEDIUM,
                'adult_height_cm' => 220,
                'adult_width_cm' => 120,
                'price' => '44.90',
                'stock_quantity' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Pittosporum du Japon',
                'species' => 'Pittosporum tobira',
                'description' => 'Un arbuste persistant pour une terrasse ou un jardin exposé à la lumière.',
                'environment' => PlantEnvironment::OUTDOOR,
                'exposure' => Exposure::SUN,
                'watering_level' => Level::MEDIUM,
                'maintenance_level' => Level::MEDIUM,
                'adult_height_cm' => 180,
                'adult_width_cm' => 120,
                'price' => '36.90',
                'stock_quantity' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Beaucarnea',
                'species' => 'Beaucarnea recurvata',
                'description' => 'Une plante sculpturale à croissance lente qui aime les intérieurs lumineux.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::SUN,
                'watering_level' => Level::LOW,
                'maintenance_level' => Level::LOW,
                'adult_height_cm' => 120,
                'adult_width_cm' => 70,
                'price' => '31.90',
                'stock_quantity' => 7,
                'is_active' => true,
            ],
            [
                'name' => 'Maranta leuconeura',
                'species' => 'Maranta leuconeura',
                'description' => 'Un feuillage mobile et décoratif pour un espace chaud à lumière tamisée.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::SHADE,
                'watering_level' => Level::HIGH,
                'maintenance_level' => Level::MEDIUM,
                'adult_height_cm' => 40,
                'adult_width_cm' => 45,
                'price' => '21.90',
                'stock_quantity' => 9,
                'is_active' => true,
            ],
            [
                'name' => 'Hoya carnosa',
                'species' => 'Hoya carnosa',
                'description' => 'Une plante grimpante aux feuilles épaisses, adaptée aux oublis d’arrosage.',
                'environment' => PlantEnvironment::INDOOR,
                'exposure' => Exposure::PARTIAL_SHADE,
                'watering_level' => Level::LOW,
                'maintenance_level' => Level::MEDIUM,
                'adult_height_cm' => 60,
                'adult_width_cm' => 45,
                'price' => '19.90',
                'stock_quantity' => 10,
                'is_active' => true,
            ],
        ];

        foreach ($plants as $plant) {
            Plant::query()->updateOrCreate(['species' => $plant['species']], $plant);
        }
    }
}
